import { CountryMapType } from "@/types/globalTypes";

export const defaultValues: { avatar: string; frontendGitHub: string; frontendIssues: string; frontendReadme: string; } = {
  avatar: process.env.NEXT_PUBLIC_DEFAULT_AVATAR_URL!,
  frontendGitHub: "https://github.com/joydeep-git/newsglance-web",
  frontendIssues: "https://github.com/joydeep-git/newsglance-web/issues",
  frontendReadme: "https://github.com/joydeep-git/newsglance-web#readme",
};


export const countryMap: Map<string, CountryMapType> = new Map([
  ["AF", { name: "Afghanistan", countrycode: "+93", currency: "AFN", flag: "🇦🇫" }],
  ["AX", { name: "Aland Islands", countrycode: "+358", currency: "EUR", flag: "🇦🇽" }],
  ["AL", { name: "Albania", countrycode: "+355", currency: "ALL", flag: "🇦🇱" }],
  ["DZ", { name: "Algeria", countrycode: "+213", currency: "DZD", flag: "🇩🇿" }],
  ["AS", { name: "American Samoa", countrycode: "+1-684", currency: "USD", flag: "🇦🇸" }],
  ["AD", { name: "Andorra", countrycode: "+376", currency: "EUR", flag: "🇦🇩" }],
  ["AO", { name: "Angola", countrycode: "+244", currency: "AOA", flag: "🇦🇴" }],
  ["AI", { name: "Anguilla", countrycode: "+1-264", currency: "XCD", flag: "🇦🇮" }],
  ["AQ", { name: "Antarctica", countrycode: "+672", currency: "N/A", flag: "🇦🇶" }],
  ["AG", { name: "Antigua and Barbuda", countrycode: "+1-268", currency: "XCD", flag: "🇦🇬" }],
  ["AR", { name: "Argentina", countrycode: "+54", currency: "ARS", flag: "🇦🇷" }],
  ["AM", { name: "Armenia", countrycode: "+374", currency: "AMD", flag: "🇦🇲" }],
  ["AW", { name: "Aruba", countrycode: "+297", currency: "AWG", flag: "🇦🇼" }],
  ["AU", { name: "Australia", countrycode: "+61", currency: "AUD", flag: "🇦🇺" }],
  ["AT", { name: "Austria", countrycode: "+43", currency: "EUR", flag: "🇦🇹" }],
  ["AZ", { name: "Azerbaijan", countrycode: "+994", currency: "AZN", flag: "🇦🇿" }],
  ["BS", { name: "Bahamas", countrycode: "+1-242", currency: "BSD", flag: "🇧🇸" }],
  ["BH", { name: "Bahrain", countrycode: "+973", currency: "BHD", flag: "🇧🇭" }],
  ["BD", { name: "Bangladesh", countrycode: "+880", currency: "BDT", flag: "🇧🇩" }],
  ["BB", { name: "Barbados", countrycode: "+1-246", currency: "BBD", flag: "🇧🇧" }],
  ["BY", { name: "Belarus", countrycode: "+375", currency: "BYN", flag: "🇧🇾" }],
  ["BE", { name: "Belgium", countrycode: "+32", currency: "EUR", flag: "🇧🇪" }],
  ["BZ", { name: "Belize", countrycode: "+501", currency: "BZD", flag: "🇧🇿" }],
  ["BJ", { name: "Benin", countrycode: "+229", currency: "XOF", flag: "🇧🇯" }],
  ["BM", { name: "Bermuda", countrycode: "+1-441", currency: "BMD", flag: "🇧🇲" }],
  ["BT", { name: "Bhutan", countrycode: "+975", currency: "BTN", flag: "🇧🇹" }],
  ["BO", { name: "Bolivia", countrycode: "+591", currency: "BOB", flag: "🇧🇴" }],
  ["BQ", { name: "Bonaire, Sint Eustatius and Saba", countrycode: "+599", currency: "USD", flag: "🇧🇶" }],
  ["BA", { name: "Bosnia and Herzegovina", countrycode: "+387", currency: "BAM", flag: "🇧🇦" }],
  ["BW", { name: "Botswana", countrycode: "+267", currency: "BWP", flag: "🇧🇼" }],
  ["BV", { name: "Bouvet Island", countrycode: "+47", currency: "NOK", flag: "🇧🇻" }],
  ["BR", { name: "Brazil", countrycode: "+55", currency: "BRL", flag: "🇧🇷" }],
  ["IO", { name: "British Indian Ocean Territory", countrycode: "+246", currency: "USD", flag: "🇮🇴" }],
  ["VG", { name: "British Virgin Islands", countrycode: "+1-284", currency: "USD", flag: "🇻🇬" }],
  ["BN", { name: "Brunei Darussalam", countrycode: "+673", currency: "BND", flag: "🇧🇳" }],
  ["BG", { name: "Bulgaria", countrycode: "+359", currency: "BGN", flag: "🇧🇬" }],
  ["BF", { name: "Burkina Faso", countrycode: "+226", currency: "XOF", flag: "🇧🇫" }],
  ["BI", { name: "Burundi", countrycode: "+257", currency: "BIF", flag: "🇧🇮" }],
  ["KH", { name: "Cambodia", countrycode: "+855", currency: "KHR", flag: "🇰🇭" }],
  ["CM", { name: "Cameroon", countrycode: "+237", currency: "XAF", flag: "🇨🇲" }],
  ["CA", { name: "Canada", countrycode: "+1", currency: "CAD", flag: "🇨🇦" }],
  ["CV", { name: "Cabo Verde", countrycode: "+238", currency: "CVE", flag: "🇨🇻" }],
  ["KY", { name: "Cayman Islands", countrycode: "+1-345", currency: "KYD", flag: "🇰🇾" }],
  ["CF", { name: "Central African Republic", countrycode: "+236", currency: "XAF", flag: "🇨🇫" }],
  ["TD", { name: "Chad", countrycode: "+235", currency: "XAF", flag: "🇹🇩" }],
  ["CL", { name: "Chile", countrycode: "+56", currency: "CLP", flag: "🇨🇱" }],
  ["CN", { name: "China", countrycode: "+86", currency: "CNY", flag: "🇨🇳" }],
  ["CX", { name: "Christmas Island", countrycode: "+61", currency: "AUD", flag: "🇨🇽" }],
  ["CC", { name: "Cocos (Keeling) Islands", countrycode: "+61", currency: "AUD", flag: "🇨🇨" }],
  ["CO", { name: "Colombia", countrycode: "+57", currency: "COP", flag: "🇨🇴" }],
  ["KM", { name: "Comoros", countrycode: "+269", currency: "KMF", flag: "🇰🇲" }],
  ["CD", { name: "Democratic Republic of the Congo", countrycode: "+243", currency: "CDF", flag: "🇨🇩" }],
  ["CG", { name: "Republic of the Congo", countrycode: "+242", currency: "XAF", flag: "🇨🇬" }],
  ["CK", { name: "Cook Islands", countrycode: "+682", currency: "NZD", flag: "🇨🇰" }],
  ["CR", { name: "Costa Rica", countrycode: "+506", currency: "CRC", flag: "🇨🇷" }],
  ["CI", { name: "Côte d'Ivoire", countrycode: "+225", currency: "XOF", flag: "🇨🇮" }],
  ["HR", { name: "Croatia", countrycode: "+385", currency: "EUR", flag: "🇭🇷" }],
  ["CU", { name: "Cuba", countrycode: "+53", currency: "CUP", flag: "🇨🇺" }],
  ["CW", { name: "Curaçao", countrycode: "+599", currency: "ANG", flag: "🇨🇼" }],
  ["CY", { name: "Cyprus", countrycode: "+357", currency: "EUR", flag: "🇨🇾" }],
  ["CZ", { name: "Czech Republic", countrycode: "+420", currency: "CZK", flag: "🇨🇿" }],
  ["DK", { name: "Denmark", countrycode: "+45", currency: "DKK", flag: "🇩🇰" }],
  ["DJ", { name: "Djibouti", countrycode: "+253", currency: "DJF", flag: "🇩🇯" }],
  ["DM", { name: "Dominica", countrycode: "+1-767", currency: "XCD", flag: "🇩🇲" }],
  ["DO", { name: "Dominican Republic", countrycode: "+1-809", currency: "DOP", flag: "🇩🇴" }],
  ["EC", { name: "Ecuador", countrycode: "+593", currency: "USD", flag: "🇪🇨" }],
  ["EG", { name: "Egypt", countrycode: "+20", currency: "EGP", flag: "🇪🇬" },],
  ["SV", { name: "El Salvador", countrycode: "+503", currency: "USD", flag: "🇸🇻" }],
  ["GQ", { name: "Equatorial Guinea", countrycode: "+240", currency: "XAF", flag: "🇬🇶" }],
  ["ER", { name: "Eritrea", countrycode: "+291", currency: "ERN", flag: "🇪🇷" }],
  ["EE", { name: "Estonia", countrycode: "+372", currency: "EUR", flag: "🇪🇪" }],
  ["SZ", { name: "Eswatini", countrycode: "+268", currency: "SZL", flag: "🇸🇿" }],
  ["ET", { name: "Ethiopia", countrycode: "+251", currency: "ETB", flag: "🇪🇹" }],
  ["FK", { name: "Falkland Islands (Malvinas)", countrycode: "+500", currency: "FKP", flag: "🇫🇰" }],
  ["FO", { name: "Faroe Islands", countrycode: "+298", currency: "DKK", flag: "🇫🇴" }],
  ["FJ", { name: "Fiji", countrycode: "+679", currency: "FJD", flag: "🇫🇯" }],
  ["FI", { name: "Finland", countrycode: "+358", currency: "EUR", flag: "🇫🇮" }],
  ["FR", { name: "France", countrycode: "+33", currency: "EUR", flag: "🇫🇷" }],
  ["GF", { name: "French Guiana", countrycode: "+594", currency: "EUR", flag: "🇬🇫" }],
  ["PF", { name: "French Polynesia", countrycode: "+689", currency: "XPF", flag: "🇵🇫" }],
  ["TF", { name: "French Southern Territories", countrycode: "+262", currency: "EUR", flag: "🇹🇫" }],
  ["GA", { name: "Gabon", countrycode: "+241", currency: "XAF", flag: "🇬🇦" }],
  ["GM", { name: "Gambia", countrycode: "+220", currency: "GMD", flag: "🇬🇲" }],
  ["GE", { name: "Georgia", countrycode: "+995", currency: "GEL", flag: "🇬🇪" }],
  ["DE", { name: "Germany", countrycode: "+49", currency: "EUR", flag: "🇩🇪" }],
  ["GH", { name: "Ghana", countrycode: "+233", currency: "GHS", flag: "🇬🇭" }],
  ["GI", { name: "Gibraltar", countrycode: "+350", currency: "GIP", flag: "🇬🇮" }],
  ["GR", { name: "Greece", countrycode: "+30", currency: "EUR", flag: "🇬🇷" }],
  ["GL", { name: "Greenland", countrycode: "+299", currency: "DKK", flag: "🇬🇱" }],
  ["GD", { name: "Grenada", countrycode: "+1-473", currency: "XCD", flag: "🇬🇩" }],
  ["GP", { name: "Guadeloupe", countrycode: "+590", currency: "EUR", flag: "🇬🇵" }],
  ["GU", { name: "Guam", countrycode: "+1-671", currency: "USD", flag: "🇬🇺" }],
  ["GT", { name: "Guatemala", countrycode: "+502", currency: "GTQ", flag: "🇬🇹" }],
  ["GG", { name: "Guernsey", countrycode: "+44", currency: "GBP", flag: "🇬🇬" }],
  ["GN", { name: "Guinea", countrycode: "+224", currency: "GNF", flag: "🇬🇳" }],
  ["GW", { name: "Guinea-Bissau", countrycode: "+245", currency: "XOF", flag: "🇬🇼" }],
  ["GY", { name: "Guyana", countrycode: "+592", currency: "GYD", flag: "🇬🇾" }],
  ["HT", { name: "Haiti", countrycode: "+509", currency: "HTG", flag: "🇭🇹" }],
  ["HM", { name: "Heard Island and McDonald Islands", countrycode: "+672", currency: "AUD", flag: "🇭🇲" }],
  ["VA", { name: "Holy See (Vatican City State)", countrycode: "+379", currency: "EUR", flag: "🇻🇦" }],
  ["HN", { name: "Honduras", countrycode: "+504", currency: "HNL", flag: "🇭🇳" }],
  ["HK", { name: "Hong Kong", countrycode: "+852", currency: "HKD", flag: "🇭🇰" }],
  ["HU", { name: "Hungary", countrycode: "+36", currency: "HUF", flag: "🇭🇺" }],
  ["IS", { name: "Iceland", countrycode: "+354", currency: "ISK", flag: "🇮🇸" }],
  ["IN", { name: "India", countrycode: "+91", currency: "INR", flag: "🇮🇳" }],
  ["ID", { name: "Indonesia", countrycode: "+62", currency: "IDR", flag: "🇮🇩" }],
  ["IR", { name: "Iran", countrycode: "+98", currency: "IRR", flag: "🇮🇷" }],
  ["IQ", { name: "Iraq", countrycode: "+964", currency: "IQD", flag: "🇮🇶" }],
  ["IE", { name: "Ireland", countrycode: "+353", currency: "EUR", flag: "🇮🇪" }],
  ["IM", { name: "Isle of Man", countrycode: "+44", currency: "GBP", flag: "🇮🇲" }],
  ["IL", { name: "Israel", countrycode: "+972", currency: "ILS", flag: "🇮🇱" }],
  ["IT", { name: "Italy", countrycode: "+39", currency: "EUR", flag: "🇮🇹" }],
  ["JM", { name: "Jamaica", countrycode: "+1-876", currency: "JMD", flag: "🇯🇲" }],
  ["JP", { name: "Japan", countrycode: "+81", currency: "JPY", flag: "🇯🇵" }],
  ["JE", { name: "Jersey", countrycode: "+44", currency: "GBP", flag: "🇯🇪" }],
  ["JO", { name: "Jordan", countrycode: "+962", currency: "JOD", flag: "🇯🇴" }],
  ["KZ", { name: "Kazakhstan", countrycode: "+7", currency: "KZT", flag: "🇰🇿" }],
  ["KE", { name: "Kenya", countrycode: "+254", currency: "KES", flag: "🇰🇪" }],
  ["KI", { name: "Kiribati", countrycode: "+686", currency: "AUD", flag: "🇰🇮" }],
  ["KP", { name: "North Korea", countrycode: "+850", currency: "KPW", flag: "🇰🇵" }],
  ["KR", { name: "South Korea", countrycode: "+82", currency: "KRW", flag: "🇰🇷" }],
  ["KW", { name: "Kuwait", countrycode: "+965", currency: "KWD", flag: "🇰🇼" }],
  ["KG", { name: "Kyrgyzstan", countrycode: "+996", currency: "KGS", flag: "🇰🇬" }],
  ["LA", { name: "Laos", countrycode: "+856", currency: "LAK", flag: "🇱🇦" }],
  ["LV", { name: "Latvia", countrycode: "+371", currency: "EUR", flag: "🇱🇻" }],
  ["LB", { name: "Lebanon", countrycode: "+961", currency: "LBP", flag: "🇱🇧" }],
  ["LS", { name: "Lesotho", countrycode: "+266", currency: "LSL", flag: "🇱🇸" }],
  ["LR", { name: "Liberia", countrycode: "+231", currency: "LRD", flag: "🇱🇷" }],
  ["LY", { name: "Libya", countrycode: "+218", currency: "LYD", flag: "🇱🇾" }],
  ["LI", { name: "Liechtenstein", countrycode: "+423", currency: "CHF", flag: "🇱🇮" }],
  ["LT", { name: "Lithuania", countrycode: "+370", currency: "EUR", flag: "🇱🇹" }],
  ["LU", { name: "Luxembourg", countrycode: "+352", currency: "EUR", flag: "🇱🇺" }],
  ["MO", { name: "Macau", countrycode: "+853", currency: "MOP", flag: "🇲🇴" }],
  ["MK", { name: "North Macedonia", countrycode: "+389", currency: "MKD", flag: "🇲🇰" }],
  ["MG", { name: "Madagascar", countrycode: "+261", currency: "MGA", flag: "🇲🇬" }],
  ["MW", { name: "Malawi", countrycode: "+265", currency: "MWK", flag: "🇲🇼" }],
  ["MY", { name: "Malaysia", countrycode: "+60", currency: "MYR", flag: "🇲🇾" }],
  ["MV", { name: "Maldives", countrycode: "+960", currency: "MVR", flag: "🇲🇻" }],
  ["ML", { name: "Mali", countrycode: "+223", currency: "XOF", flag: "🇲🇱" }],
  ["MT", { name: "Malta", countrycode: "+356", currency: "EUR", flag: "🇲🇹" }],
  ["MH", { name: "Marshall Islands", countrycode: "+692", currency: "USD", flag: "🇲🇭" }],
  ["MQ", { name: "Martinique", countrycode: "+596", currency: "EUR", flag: "🇲🇶" }],
  ["MR", { name: "Mauritania", countrycode: "+222", currency: "MRU", flag: "🇲🇷" }],
  ["MU", { name: "Mauritius", countrycode: "+230", currency: "MUR", flag: "🇲🇺" }],
  ["YT", { name: "Mayotte", countrycode: "+262", currency: "EUR", flag: "🇾🇹" }],
  ["MX", { name: "Mexico", countrycode: "+52", currency: "MXN", flag: "🇲🇽" }],
  ["FM", { name: "Federated States of Micronesia", countrycode: "+691", currency: "USD", flag: "🇫🇲" }],
  ["MD", { name: "Moldova", countrycode: "+373", currency: "MDL", flag: "🇲🇩" }],
  ["MC", { name: "Monaco", countrycode: "+377", currency: "EUR", flag: "🇲🇨" }],
  ["MN", { name: "Mongolia", countrycode: "+976", currency: "MNT", flag: "🇲🇳" }],
  ["ME", { name: "Montenegro", countrycode: "+382", currency: "EUR", flag: "🇲🇪" }],
  ["MS", { name: "Montserrat", countrycode: "+1-664", currency: "XCD", flag: "🇲🇸" }],
  ["MA", { name: "Morocco", countrycode: "+212", currency: "MAD", flag: "🇲🇦" }],
  ["MZ", { name: "Mozambique", countrycode: "+258", currency: "MZN", flag: "🇲🇿" }],
  ["MM", { name: "Myanmar", countrycode: "+95", currency: "MMK", flag: "🇲🇲" }],
  ["NA", { name: "Namibia", countrycode: "+264", currency: "NAD", flag: "🇳🇦" }],
  ["NR", { name: "Nauru", countrycode: "+674", currency: "AUD", flag: "🇳🇷" }],
  ["NP", { name: "Nepal", countrycode: "+977", currency: "NPR", flag: "🇳🇵" }],
  ["NL", { name: "Netherlands", countrycode: "+31", currency: "EUR", flag: "🇳🇱" }],
  ["NC", { name: "New Caledonia", countrycode: "+687", currency: "XPF", flag: "🇳🇨" }],
  ["NZ", { name: "New Zealand", countrycode: "+64", currency: "NZD", flag: "🇳🇿" }],
  ["NI", { name: "Nicaragua", countrycode: "+505", currency: "NIO", flag: "🇳🇮" }],
  ["NE", { name: "Niger", countrycode: "+227", currency: "XOF", flag: "🇳🇪" }],
  ["NG", { name: "Nigeria", countrycode: "+234", currency: "NGN", flag: "🇳🇬" }],
  ["NU", { name: "Niue", countrycode: "+683", currency: "NZD", flag: "🇳🇺" }],
  ["NF", { name: "Norfolk Island", countrycode: "+672", currency: "AUD", flag: "🇳🇫" }],
  ["MP", { name: "Northern Mariana Islands", countrycode: "+1-670", currency: "USD", flag: "🇲🇵" }],
  ["NO", { name: "Norway", countrycode: "+47", currency: "NOK", flag: "🇳🇴" }],
  ["OM", { name: "Oman", countrycode: "+968", currency: "OMR", flag: "🇴🇲" }],
  ["PK", { name: "Pakistan", countrycode: "+92", currency: "PKR", flag: "🇵🇰" }],
  ["PW", { name: "Palau", countrycode: "+680", currency: "USD", flag: "🇵🇼" }],
  ["PS", { name: "Palestine, State of", countrycode: "+970", currency: "ILS", flag: "🇵🇸" }],
  ["PA", { name: "Panama", countrycode: "+507", currency: "PAB", flag: "🇵🇦" }],
  ["PG", { name: "Papua New Guinea", countrycode: "+675", currency: "PGK", flag: "🇵🇬" }],
  ["PY", { name: "Paraguay", countrycode: "+595", currency: "PYG", flag: "🇵🇾" }],
  ["PE", { name: "Peru", countrycode: "+51", currency: "PEN", flag: "🇵🇪" }],
  ["PH", { name: "Philippines", countrycode: "+63", currency: "PHP", flag: "🇵🇭" }],
  ["PN", { name: "Pitcairn Islands", countrycode: "+64", currency: "NZD", flag: "🇵🇳" }],
  ["PL", { name: "Poland", countrycode: "+48", currency: "PLN", flag: "🇵🇱" }],
  ["PT", { name: "Portugal", countrycode: "+351", currency: "EUR", flag: "🇵🇹" }],
  ["PR", { name: "Puerto Rico", countrycode: "+1-787", currency: "USD", flag: "🇵🇷" }],
  ["QA", { name: "Qatar", countrycode: "+974", currency: "QAR", flag: "🇶🇦" }],
  ["RE", { name: "Réunion", countrycode: "+262", currency: "EUR", flag: "🇷🇪" }],
  ["RO", { name: "Romania", countrycode: "+40", currency: "RON", flag: "🇷🇴" }],
  ["RU", { name: "Russia", countrycode: "+7", currency: "RUB", flag: "🇷🇺" }],
  ["RW", { name: "Rwanda", countrycode: "+250", currency: "RWF", flag: "🇷🇼" }],
  ["BL", { name: "Saint Barthélemy", countrycode: "+590", currency: "EUR", flag: "🇧🇱" }],
  ["SH", { name: "Saint Helena", countrycode: "+290", currency: "SHP", flag: "🇸🇭" }],
  ["KN", { name: "Saint Kitts and Nevis", countrycode: "+1-869", currency: "XCD", flag: "🇰🇳" }],
  ["LC", { name: "Saint Lucia", countrycode: "+1-758", currency: "XCD", flag: "🇱🇨" }],
  ["MF", { name: "Saint Martin", countrycode: "+590", currency: "EUR", flag: "🇲🇫" }],
  ["PM", { name: "Saint Pierre and Miquelon", countrycode: "+508", currency: "EUR", flag: "🇵🇲" }],
  ["VC", { name: "Saint Vincent and the Grenadines", countrycode: "+1-784", currency: "XCD", flag: "🇻🇨" }],
  ["WS", { name: "Samoa", countrycode: "+685", currency: "WST", flag: "🇼🇸" }],
  ["SM", { name: "San Marino", countrycode: "+378", currency: "EUR", flag: "🇸🇲" }],
  ["ST", { name: "São Tomé and Príncipe", countrycode: "+239", currency: "STN", flag: "🇸🇹" }],
  ["SA", { name: "Saudi Arabia", countrycode: "+966", currency: "SAR", flag: "🇸🇦" }],
  ["SN", { name: "Senegal", countrycode: "+221", currency: "XOF", flag: "🇸🇳" }],
  ["RS", { name: "Serbia", countrycode: "+381", currency: "RSD", flag: "🇷🇸" }],
  ["SC", { name: "Seychelles", countrycode: "+248", currency: "SCR", flag: "🇸🇨" }],
  ["SL", { name: "Sierra Leone", countrycode: "+232", currency: "SLL", flag: "🇸🇱" }],
  ["SG", { name: "Singapore", countrycode: "+65", currency: "SGD", flag: "🇸🇬" }],
  ["SX", { name: "Sint Maarten", countrycode: "+1-721", currency: "ANG", flag: "🇸🇽" }],
  ["SK", { name: "Slovakia", countrycode: "+421", currency: "EUR", flag: "🇸🇰" }],
  ["SI", { name: "Slovenia", countrycode: "+386", currency: "EUR", flag: "🇸🇮" }],
  ["SB", { name: "Solomon Islands", countrycode: "+677", currency: "SBD", flag: "🇸🇧" }],
  ["SO", { name: "Somalia", countrycode: "+252", currency: "SOS", flag: "🇸🇴" }],
  ["ZA", { name: "South Africa", countrycode: "+27", currency: "ZAR", flag: "🇿🇦" }],
  ["GS", { name: "South Georgia and the South Sandwich Islands", countrycode: "+500", currency: "GBP", flag: "🇬🇸" }],
  ["SS", { name: "South Sudan", countrycode: "+211", currency: "SSP", flag: "🇸🇸" }],
  ["ES", { name: "Spain", countrycode: "+34", currency: "EUR", flag: "🇪🇸" }],
  ["LK", { name: "Sri Lanka", countrycode: "+94", currency: "LKR", flag: "🇱🇰" }],
  ["SD", { name: "Sudan", countrycode: "+249", currency: "SDG", flag: "🇸🇩" }],
  ["SR", { name: "Suriname", countrycode: "+597", currency: "SRD", flag: "🇸🇷" }],
  ["SJ", { name: "Svalbard and Jan Mayen", countrycode: "+47", currency: "NOK", flag: "🇸🇯" }],
  ["SE", { name: "Sweden", countrycode: "+46", currency: "SEK", flag: "🇸🇪" }],
  ["CH", { name: "Switzerland", countrycode: "+41", currency: "CHF", flag: "🇨🇭" }],
  ["SY", { name: "Syria", countrycode: "+963", currency: "SYP", flag: "🇸🇾" }],
  ["TW", { name: "Taiwan", countrycode: "+886", currency: "TWD", flag: "🇹🇼" }],
  ["TJ", { name: "Tajikistan", countrycode: "+992", currency: "TJS", flag: "🇹🇯" }],
  ["TZ", { name: "Tanzania", countrycode: "+255", currency: "TZS", flag: "🇹🇿" }],
  ["TH", { name: "Thailand", countrycode: "+66", currency: "THB", flag: "🇹🇭" }],
  ["TL", { name: "Timor-Leste", countrycode: "+670", currency: "USD", flag: "🇹🇱" }],
  ["TG", { name: "Togo", countrycode: "+228", currency: "XOF", flag: "🇹🇬" }],
  ["TK", { name: "Tokelau", countrycode: "+690", currency: "NZD", flag: "🇹🇰" }],
  ["TO", { name: "Tonga", countrycode: "+676", currency: "TOP", flag: "🇹🇴" }],
  ["TT", { name: "Trinidad and Tobago", countrycode: "+1-868", currency: "TTD", flag: "🇹🇹" }],
  ["TN", { name: "Tunisia", countrycode: "+216", currency: "TND", flag: "🇹🇳" }],
  ["TR", { name: "Turkey", countrycode: "+90", currency: "TRY", flag: "🇹🇷" }],
  ["TM", { name: "Turkmenistan", countrycode: "+993", currency: "TMT", flag: "🇹🇲" }],
  ["TC", { name: "Turks and Caicos Islands", countrycode: "+1-649", currency: "USD", flag: "🇹🇨" }],
  ["TV", { name: "Tuvalu", countrycode: "+688", currency: "AUD", flag: "🇹🇻" }],
  ["UG", { name: "Uganda", countrycode: "+256", currency: "UGX", flag: "🇺🇬" }],
  ["UA", { name: "Ukraine", countrycode: "+380", currency: "UAH", flag: "🇺🇦" }],
  ["AE", { name: "United Arab Emirates", countrycode: "+971", currency: "AED", flag: "🇦🇪" }],
  ["GB", { name: "United Kingdom", countrycode: "+44", currency: "GBP", flag: "🇬🇧" }],
  ["US", { name: "United States", countrycode: "+1", currency: "USD", flag: "🇺🇸" }],
  ["UM", { name: "U.S. Minor Outlying Islands", countrycode: "+1", currency: "USD", flag: "🇺🇲" }],
  ["UY", { name: "Uruguay", countrycode: "+598", currency: "UYU", flag: "🇺🇾" }],
  ["UZ", { name: "Uzbekistan", countrycode: "+998", currency: "UZS", flag: "🇺🇿" }],
  ["VU", { name: "Vanuatu", countrycode: "+678", currency: "VUV", flag: "🇻🇺" }],
  ["VE", { name: "Venezuela", countrycode: "+58", currency: "VES", flag: "🇻🇪" }],
  ["VN", { name: "Vietnam", countrycode: "+84", currency: "VND", flag: "🇻🇳" }],
  ["VI", { name: "U.S. Virgin Islands", countrycode: "+1-340", currency: "USD", flag: "🇻🇮" }],
  ["WF", { name: "Wallis and Futuna", countrycode: "+681", currency: "XPF", flag: "🇼🇫" }],
  ["EH", { name: "Western Sahara", countrycode: "+212", currency: "MAD", flag: "🇪🇭" }],
  ["YE", { name: "Yemen", countrycode: "+967", currency: "YER", flag: "🇾🇪" }],
  ["ZM", { name: "Zambia", countrycode: "+260", currency: "ZMW", flag: "🇿🇲" }],
  ["ZW", { name: "Zimbabwe", countrycode: "+263", currency: "USD", flag: "🇿🇼" }]
]);



export const newsCategories = {
  "technology": "Tech",
  "business": "Business",
  "money": "Finance",
  "sport": "Sports",
  "culture": "Entertainment",
  "politics": "Politics",
  "fashion": "Fashion",
  "travel": "Travel",
  "lifeandstyle": "Health",
};
